/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookShop;

import javax.swing.JOptionPane;

/**
 *
 * @author Cemre Şenyuva, Enes Pusa
 */
public class AdminLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form adminGUI
     */
    public AdminLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        adminName = new javax.swing.JTextField();
        adminPassword = new javax.swing.JPasswordField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        userTF10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel15.setBackground(new java.awt.Color(186, 79, 84));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminName.setBackground(new java.awt.Color(186, 79, 84));
        adminName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        adminName.setForeground(new java.awt.Color(255, 255, 255));
        adminName.setText("Kullanıcı adı");
        adminName.setBorder(null);
        adminName.setCaretColor(new java.awt.Color(255, 255, 255));
        adminName.setCaretPosition(8);
        adminName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminNameFocusGained(evt);
            }
        });
        jPanel15.add(adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        adminPassword.setBackground(new java.awt.Color(186, 79, 84));
        adminPassword.setForeground(new java.awt.Color(255, 255, 255));
        adminPassword.setText("Şifre");
        adminPassword.setBorder(null);
        adminPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        adminPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminPasswordFocusGained(evt);
            }
        });
        jPanel15.add(adminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 30));

        jSeparator19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        jSeparator20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, -1));
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 40));
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 40));

        jPanel16.setBackground(new java.awt.Color(186, 79, 84));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));

        login.setForeground(new java.awt.Color(204, 204, 204));
        login.setText("         Giriş yap");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 40));

        jLabel31.setBackground(new java.awt.Color(186, 79, 84));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("    X ");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, 40));

        userTF10.setBackground(new java.awt.Color(186, 79, 84));
        userTF10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userTF10.setForeground(new java.awt.Color(255, 255, 255));
        userTF10.setText("Kullanıcı adı");
        userTF10.setBorder(null);
        userTF10.setCaretColor(new java.awt.Color(255, 255, 255));
        userTF10.setCaretPosition(8);
        userTF10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTF10FocusGained(evt);
            }
        });
        userTF10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF10ActionPerformed(evt);
            }
        });
        jPanel15.add(userTF10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));
        jPanel15.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 40, 40));
        jPanel15.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTF10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF10ActionPerformed

    private void userTF10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTF10FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF10FocusGained

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        AdminLogin admin = new AdminLogin(adminName.getText(), adminPassword.getText());
        if ( admin.login() ){
            dispose();
            AdminScreenGUI adminLoginScreen = new AdminScreenGUI();
            adminLoginScreen.show();
        }
        else{
            JOptionPane.showMessageDialog(null, "Admin girişi başarısız");
        }
    }//GEN-LAST:event_loginMouseClicked

    private void adminPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminPasswordFocusGained
        adminPassword.setText("");
    }//GEN-LAST:event_adminPasswordFocusGained

    private void adminNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminNameFocusGained
        adminName.setText("");
    }//GEN-LAST:event_adminNameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminName;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JLabel login;
    private javax.swing.JTextField userTF10;
    // End of variables declaration//GEN-END:variables
}
