/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookShop;

import javax.swing.JOptionPane;
import static bookShop.ShoppingBasket.shopping_basket;
import static bookShop.CustomerSignUp.signUp;
/**
 *
 * @author Cemre Şenyuva, Enes Pusa
 */
public class CustomerLoginGUI extends javax.swing.JFrame {
   
    /**
     * Creates new form GirisGUI
     */
    public CustomerLoginGUI() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        userTF7 = new javax.swing.JTextField();
        passTF6 = new javax.swing.JPasswordField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        userTF8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        signupName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        signUpPassword = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        signUpButton = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        signUpMail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        loginMail = new javax.swing.JTextField();
        loginPassword = new javax.swing.JPasswordField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        loginButton = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        userTF10 = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTF7.setBackground(new java.awt.Color(186, 79, 84));
        userTF7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userTF7.setForeground(new java.awt.Color(255, 255, 255));
        userTF7.setText("Kullanıcı adı");
        userTF7.setBorder(null);
        userTF7.setCaretColor(new java.awt.Color(255, 255, 255));
        userTF7.setCaretPosition(8);
        userTF7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTF7FocusGained(evt);
            }
        });
        userTF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF7ActionPerformed(evt);
            }
        });
        jPanel3.add(userTF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        passTF6.setBackground(new java.awt.Color(186, 79, 84));
        passTF6.setForeground(new java.awt.Color(255, 255, 255));
        passTF6.setText("Şifre");
        passTF6.setBorder(null);
        passTF6.setCaretColor(new java.awt.Color(255, 255, 255));
        passTF6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTF6FocusGained(evt);
            }
        });
        jPanel3.add(passTF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 30));

        jSeparator17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        jSeparator18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, -1));
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 40));
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 30, 40));

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("         Giriş yap");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 40));

        jLabel27.setBackground(new java.awt.Color(186, 79, 84));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("    X ");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 50, 40));

        userTF8.setBackground(new java.awt.Color(186, 79, 84));
        userTF8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userTF8.setForeground(new java.awt.Color(255, 255, 255));
        userTF8.setText("Kullanıcı adı");
        userTF8.setBorder(null);
        userTF8.setCaretColor(new java.awt.Color(255, 255, 255));
        userTF8.setCaretPosition(8);
        userTF8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTF8FocusGained(evt);
            }
        });
        userTF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF8ActionPerformed(evt);
            }
        });
        jPanel3.add(userTF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        signupName.setBackground(new java.awt.Color(255, 255, 234));
        signupName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        signupName.setForeground(new java.awt.Color(51, 51, 51));
        signupName.setText("Ad Soyad");
        signupName.setBorder(null);
        signupName.setCaretColor(new java.awt.Color(255, 255, 255));
        signupName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signupNameFocusGained(evt);
            }
        });
        signupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupNameActionPerformed(evt);
            }
        });
        jPanel2.add(signupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, 30));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        signUpPassword.setBackground(new java.awt.Color(255, 255, 234));
        signUpPassword.setForeground(new java.awt.Color(51, 51, 51));
        signUpPassword.setText("Şifre");
        signUpPassword.setBorder(null);
        signUpPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        signUpPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpPasswordFocusGained(evt);
            }
        });
        jPanel2.add(signUpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 40));

        signUpButton.setBackground(new java.awt.Color(255, 255, 255));
        signUpButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(51, 51, 51));
        signUpButton.setText("        Kayıt ol");
        signUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });
        jPanel2.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 100, 40));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 282, 250, 10));

        signUpMail.setBackground(new java.awt.Color(255, 255, 234));
        signUpMail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        signUpMail.setForeground(new java.awt.Color(51, 51, 51));
        signUpMail.setText("Email");
        signUpMail.setBorder(null);
        signUpMail.setCaretColor(new java.awt.Color(255, 255, 255));
        signUpMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpMailFocusGained(evt);
            }
        });
        signUpMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpMailActionPerformed(evt);
            }
        });
        jPanel2.add(signUpMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 30, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 471, 475));

        jPanel15.setBackground(new java.awt.Color(186, 79, 84));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginMail.setBackground(new java.awt.Color(186, 79, 84));
        loginMail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        loginMail.setForeground(new java.awt.Color(255, 255, 255));
        loginMail.setText("Email");
        loginMail.setBorder(null);
        loginMail.setCaretColor(new java.awt.Color(255, 255, 255));
        loginMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginMailFocusGained(evt);
            }
        });
        loginMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMailActionPerformed(evt);
            }
        });
        jPanel15.add(loginMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        loginPassword.setBackground(new java.awt.Color(186, 79, 84));
        loginPassword.setForeground(new java.awt.Color(255, 255, 255));
        loginPassword.setText("Şifre");
        loginPassword.setBorder(null);
        loginPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        loginPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPasswordFocusGained(evt);
            }
        });
        jPanel15.add(loginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 30));

        jSeparator19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        jSeparator20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, -1));
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 40));
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 30, 40));

        jPanel16.setBackground(new java.awt.Color(186, 79, 84));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginButton.setForeground(new java.awt.Color(204, 204, 204));
        loginButton.setText("         Giriş yap");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 40));

        jLabel31.setBackground(new java.awt.Color(186, 79, 84));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("    X ");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 50, 40));

        userTF10.setBackground(new java.awt.Color(186, 79, 84));
        userTF10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userTF10.setForeground(new java.awt.Color(255, 255, 255));
        userTF10.setText("Kullanıcı adı");
        userTF10.setBorder(null);
        userTF10.setCaretColor(new java.awt.Color(255, 255, 255));
        userTF10.setCaretPosition(8);
        userTF10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTF10FocusGained(evt);
            }
        });
        userTF10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF10ActionPerformed(evt);
            }
        });
        jPanel15.add(userTF10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 0, 480, 475));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signupNameFocusGained
       signupName.setText("");
    }//GEN-LAST:event_signupNameFocusGained

    private void signupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupNameActionPerformed
        signupName.setText("");
    }//GEN-LAST:event_signupNameActionPerformed

    private void signUpPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPasswordFocusGained
        signUpPassword.setText("");
    }//GEN-LAST:event_signUpPasswordFocusGained

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        signUp = new CustomerSignUp(signupName.getText(),signUpMail.getText(),signUpPassword.getText());
        signUp.signUp(signUp);
    }//GEN-LAST:event_signUpButtonMouseClicked

    private void signUpMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpMailFocusGained
        signUpMail.setText("");
    }//GEN-LAST:event_signUpMailFocusGained

    private void signUpMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpMailActionPerformed

    private void userTF7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTF7FocusGained
   
    }//GEN-LAST:event_userTF7FocusGained

    private void userTF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF7ActionPerformed

    private void passTF6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTF6FocusGained
       
    }//GEN-LAST:event_passTF6FocusGained

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
    
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void userTF8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTF8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF8FocusGained

    private void userTF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF8ActionPerformed

    private void loginMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginMailFocusGained
        loginMail.setText("");
    }//GEN-LAST:event_loginMailFocusGained

    private void loginMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMailActionPerformed

    private void loginPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPasswordFocusGained
       loginPassword.setText("");
    }//GEN-LAST:event_loginPasswordFocusGained

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        CustomerLogin login = new CustomerLogin(loginMail.getText(),loginPassword.getText());
        if (login.login()){
            
            dispose();
            CustomerShoppingGUI customerScreen = new CustomerShoppingGUI();
            
            shopping_basket=new ShoppingBasket();
            customerScreen.show();
        }
        else{
            JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış.");
        }
        
    }//GEN-LAST:event_loginButtonMouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void userTF10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTF10FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF10FocusGained

    private void userTF10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel loginButton;
    private javax.swing.JTextField loginMail;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JPasswordField passTF6;
    private javax.swing.JLabel signUpButton;
    private javax.swing.JTextField signUpMail;
    private javax.swing.JPasswordField signUpPassword;
    private javax.swing.JTextField signupName;
    private javax.swing.JTextField userTF10;
    private javax.swing.JTextField userTF7;
    private javax.swing.JTextField userTF8;
    // End of variables declaration//GEN-END:variables
}
